language: php

php:
- 5.6
- 7.0
- 7.1
- 7.2

dist: trusty
sudo: false

before_script:
- printf 'yes\nno\nyes\nno\nno\nno\nno\n' | pecl install swoole
- composer install --prefer-dist

script: vendor/bin/phpunit --verbose
